// Indian regional languages (scheduled + widely spoken)
export const REGIONAL_LANGUAGES = [
    "Assamese",
    "Bengali",
    "Bodo",
    "Dogri",
    "Gujarati",
    "Hindi",
    "Kannada",
    "Kashmiri",
    "Konkani",
    "Maithili",
    "Malayalam",
    "Manipuri (Meitei)",
    "Marathi",
    "Nepali",
    "Odia",
    "Punjabi",
    "Sanskrit",
    "Santali",
    "Sindhi",
    "Tamil",
    "Telugu",
    "Urdu",
    "Bhojpuri",
    "Chhattisgarhi",
    "Haryanvi",
    "Kumaoni",
    "Magahi",
    "Rajasthani",
    "Tulu",
];
